name: Build and Test
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v5.0.0
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npx nypm@latest i

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Install playwright deps
        run: pnpm exec playwright install-deps

      - name: Install playwright
        run: pnpm exec playwright-core install

      - name: Run linting
        run: pnpm lint

      - name: Prepare Nuxt
        run: pnpm dev:prepare

      - name: Run tests
        run: pnpm test

      - name: Build package
        run: pnpm prepack
